### PR TITLE
Add support to gradle 7 to Critter plugin

### PR DESCRIPTION
**Pull request by KernelFreeze**
Fixed an error when trying to use the plugin with Gradle 7.

### CODE REVIEW

**Comment by evanchooly** [comment]
First, thanks for the PR and taking the time to contribute.  But this change actually breaks some of the variable initialization inside the gradle code so it'll need a bit more work.  What is broken exactly using gradle 7?

**Comment by KernelFreeze** [comment]
Using Gradle 7 you get the following error:

```
Some problems were found with the configuration of task ':critter' (type 'CritterTask').
  - In plugin 'dev.morphia.critter' type 'dev.morphia.critter.CritterTask' property 'criteriaPackage' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.1.1/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

**Comment by evanchooly** [comment]
manually "merged" this PR in the process of other fixes.  apologies for the delay.

**Comment by KernelFreeze** [comment]
Thank you so much!

**Pull request closed without merging**
